export type Locale = "en" | "tc";
const tc: Record<string, string> = {
  "Whitepaper chapters":"白皮書章節", "VERSION 1.1":"版本 1.1", "REVIEW DRAFT":"審核稿", "WHITEPAPER":"白皮書", "Start here":"從這裡開始", "The ecosystem":"生態系統", "Resources":"資源", "Overview":"概覽", "Network Architecture":"網絡架構", "MHA Tokenomics":"MHA 代幣經濟", "Governance":"治理", "Developer Guides":"開發者指南", "Revision disclosures":"修訂披露", "All chapters":"全部章節", "W3 ecosystem":"W3 生態", "Learning & economics":"基礎與代幣經濟", "Networks":"網絡", "Architecture & solutions":"架構與方案", "Developer guides":"開發者指南", "Help & reference":"說明與參考", "Community":"社群", "Search whitepaper":"搜尋白皮書", "No matching chapters":"找不到符合的章節", "Try “tokenomics”, “testnet” or “governance”.":"試試「代幣經濟」、「測試網」或「治理」。", "Skip to content":"跳至正文", "MAGNE.AI Whitepaper home":"MAGNE.AI 白皮書首頁", "v1.0 Original":"v1.0 原版", "Open chapter navigation":"開啟章節目錄", "Close chapter navigation":"關閉章節目錄", "On this page":"本頁目錄", "MAGNE.AI Whitepaper · v1.1 review draft":"MAGNE.AI 白皮書 · v1.1 審核稿", "Revision history":"修訂紀錄", "Chapters":"章節", "Revision notes":"修訂說明", "Whitepaper":"白皮書", "A reference for the MAGNE.AI ecosystem.":"MAGNE.AI 生態系統參考文件。", "Network architecture, token economics and implementation disclosures.":"網絡架構、代幣經濟與執行披露。", "Read v1.1":"閱讀 v1.1", "Explore the whitepaper contents":"探索白皮書內容", "Version 1.1":"版本 1.1", "Revision scope":"修訂範圍", "Updated Exchange Campaigns and liquidity implementation rules.":"更新交易所活動及流動性執行規則。", "Total supply and top-level allocations unchanged.":"總供應量及頂層分配維持不變。", "What changed":"修訂內容", "Purpose, scope and key elements of the MAGNE.AI ecosystem.":"MAGNE.AI 生態系統的目標、範圍與核心要素。", "System design, core components and network operation.":"系統設計、核心元件與網絡運作。", "Allocation, release rules and post-TGE execution disclosures.":"分配、釋放規則與 TGE 後執行披露。", "Governance structure, participants and processes.":"治理架構、參與者及流程。", "Technical resources, integration guides and references.":"技術資源、整合指南與參考資料。", "Chapter pagination":"章節導覽", "Previous chapter":"上一章", "Next chapter":"下一章", "Whitepaper overview":"白皮書概覽",
};
export function translate(text: string, locale: Locale) { return locale === "tc" ? tc[text] ?? text : text; }
export function localizeHref(href: string, locale: Locale) {
  if(locale !== "tc" || !href.startsWith('/') || href.startsWith('/v1.0') || href.startsWith('/tc')) return href;
  return href === '/' ? '/tc/' : '/tc'+href;
}
export function originalPath(path: string) { return path.replace(/^\/tc(?=\/|$)/,'') || '/'; }
